### ISSUE TITLE
Wrong README

### ISSUE THREAD

**Issue by KetchuppOfficial** [flopsreallygotit/Stack#1]
Hi, flopsreallygotit!

I was curious how freshmen solve tasks by Ded this year. So I tried to install your stack according to README. Unfortunately, I failed because of a mistake in your building manual.

Look what I've got:
![issue](https://user-images.githubusercontent.com/83651035/195911233-e15fe547-86d3-496e-990a-ebdd9e66d9f1.png)

Hope you'll fix this.

With best regards, KetchuppOfficial

**Comment by flopsreallygotit** [comment]
Hi, Ketchupp. Thank you for your attention! You're right, manual is wrong. I'll fix it soon. 
Good Luck && Best differentiation && Unforgettable RT-bebri

**Comment by flopsreallygotit** [comment]
Fix it
