### ISSUE TITLE
You've been hacked :-)

### ISSUE THREAD

**Issue by KetchuppOfficial** [flopsreallygotit/Stack#2]
Hi, flopsreallygotit!

Don't worry, I figured out how to build and run your program (but it would be nice to fix README anyway). Unfortunately, it's incredibly easy to hack your stack. Look at this code:
```C
#include "stackUtils.h"
#include "math.h"

int main ()
{   
    stack good_luck = {};
    stackConstructor (&good_luck, 10);
    good_luck.data = NULL;
    stackDestructor (&good_luck);

    return 0;
}
```
The result is beloved segmentation fault :-)

I recommend you to learn something about encapsulation and how it should be implemented in C. You can start here: https://en.wikipedia.org/wiki/Encapsulation_(computer_programming).

With best regards, KetchuppOfficial

**Comment by flopsreallygotit** [comment]
Hi, Ketchupp. Thank you for your attention and activity! I'll try to fix it as soon as possible.

**Comment by flopsreallygotit** [comment]
Hi, Ketchupp! I fixed it :-) Thanks a lot!
