### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by KetchuppOfficial** [flopsreallygotit/Stack#3]
Hi, flopsreallygotit!

I tested your stack on the given example. Sadly, I noticed bad memory leaks:
![Screenshot from 2022-11-01 01-40-23](https://user-images.githubusercontent.com/83651035/199123411-8227225b-9748-4797-9a06-4c71d5d26851.png)

Hope you'll add all missing free() calls.

With best regards, KetchuppOfficial

**Comment by flopsreallygotit** [comment]
Hi, Ketchupp! Thank you for your activity and help! Fixed it :-)
